### PR TITLE
Add IMEI tag

### PR DESCRIPTION
**Pull request by Naylin15**
Hi @ajsb85 @g-bougard @Ivans51

This PR adds the IME tag to the Modems component

Thank you

## Estimated time
|Assignee | 🍅|
|-- | --|
|@Naylin15|1|

Related:

[#188](https://github.com/flyve-mdm/android-inventory-library/issues/188), [#193](https://github.com/flyve-mdm/android-inventory-library/pull/193), [#198](https://github.com/flyve-mdm/android-inventory-library/issues/198), [#58](https://github.com/fusioninventory/fusioninventory.github.io/pull/58)

### CODE REVIEW

**Comment by Naylin15** [comment]
Hi @ajsb85,

IMEI added in json inventory

Thank you

**Comment by g-bougard** [comment]
Hi @trasher 
this still was merged on fusioninventory.org, see [#58](https://github.com/fusioninventory/fusioninventory.github.io/pull/58) from the related links.
I'm okay with this PR.

**Comment by trasher** [comment]
OK, thank you :)

**Comment by trasher** [comment]
I've reverted, it seems it may not be correct; ping @btry

**Comment by btry** [comment]
hi,

I confirm. We need to gather information about the ability for a single modem to have several IMEI. Currenty this case is highly probable.

**Pull request merged**
