### PR TITLE
fix(date): convert OS boot time

### PR DESCRIPTION
**Pull request by stonebuzz**
Prevent SQL error

```sql
[2022-10-19 08:25:33] glpisqllog.ERROR: DBmysql::query() in /home/GLPI/10.0-bugfixes/src/DBmysql.php line 370
  *** MySQL query error:
  SQL: UPDATE `glpi_computers` SET `last_boot` = '2022-21-09 05:21:23' WHERE `id` = '40'
  Error: Incorrect datetime value: '2022-21-09 05:21:23' for column `10bugfixes`.`glpi_computers`.`last_boot` at row 1
  Backtrace :
  src/DBmysql.php:1431                               
  src/CommonDBTM.php:675                             DBmysql->update()
  src/CommonDBTM.php:1678                            CommonDBTM->updateInDB()
  src/Inventory/Asset/MainAsset.php:774              CommonDBTM->update()
  src/RuleImportAsset.php:950                        Glpi\Inventory\Asset\MainAsset->rulepassed()
  src/Rule.php:1510                                  RuleImportAsset->executeActions()
  src/RuleCollection.php:1591                        Rule->process()
  src/Inventory/Asset/MainAsset.php:565              RuleCollection->processAllRules()
  src/Inventory/Inventory.php:702                    Glpi\Inventory\Asset\MainAsset->handle()
  src/Inventory/Inventory.php:337                    Glpi\Inventory\Inventory->handleItem()
  src/Inventory/Request.php:360                      Glpi\Inventory\Inventory->doInventory()
  src/Inventory/Request.php:90                       Glpi\Inventory\Request->inventory()
  src/Agent/Communication/AbstractRequest.php:305    Glpi\Inventory\Request->handleAction()
  src/Agent/Communication/AbstractRequest.php:242    Glpi\Agent\Communication\AbstractRequest->handleXMLRequest()
  src/Inventory/Conf.php:251                         Glpi\Agent\Communication\AbstractRequest->handleRequest()
  src/Inventory/Conf.php:192                         Glpi\Inventory\Conf->importContentFile()
  front/inventory.conf.php:47                        Glpi\Inventory\Conf->importFile()
  {"user":"2@stanislas-asus-desktop"} 
```

Android inventory (XML) have ```Y-d-m H:i:s``` format -> ```KO```
GLPI-agent have (JSON) ```Y-m-d H:i:s``` format -> ```OK```
FusionInventory (XML)  have ```Y-d-m H:i:s``` format -> ```KO```

This PR unify format from inventory to get ```Y-d-m```

### CODE REVIEW

**Comment by trasher** [comment]
Maybe a test should be added to make sure?

**Review by trasher — APPROVED** [review]

**Review by cedric-anne — APPROVED** [review]

**Review by cedric-anne — CHANGES_REQUESTED** [review]
It cannot work with current implementation of `Converter::convertDate()`. Indeed `DateTime::createFromFormat("Y-m-d", "2022-21-09");` will not fail and will result in a `2022-09-09` date, so it will not reach other formats.

**Comment by stonebuzz** [comment]
The format ```Y-d-m H:i:s``` was missing, to allow the converter to transform this date format into ```Y-m-d H:i:s```

**Comment by cedric-anne** [comment]
> The format `Y-d-m H:i:s` was missing, to allow the converter to transform this date format into `Y-m-d H:i:s`

As explained in my previous comment, it cannot work.

**Comment by trasher** [comment]
> > The format `Y-d-m H:i:s` was missing, to allow the converter to transform this date format into `Y-m-d H:i:s`
> 
> As explained in my previous comment, it cannot work.

I agree. The "new" format takes precedence on others existing, and will breaks known working cases.

**Review by trasher — APPROVED** [review]

**Review by cedric-anne — COMMENTED** [review]
I am not sure this is a good idea to do it like that. Indeed, prior to this change, if date was `2022-10-12 10:26:43` , result was a `Nov 12th`, and now it will be `Dec 10th`. All dates having a day `<= 12` will now be considered as `Y-d-m` dates, but I guess all of them are `Y-m-d` date with new version of the GLPI Agent.

**Comment by trasher** [comment]
Since this is limited to last boot only, and it seems always wrongly formatted the same way; I guess this is oky.

**Review by cedric-anne — APPROVED** [review]

**Pull request merged**
